### ISSUE TITLE
Some settings are invisible and missing expand button.

### ISSUE THREAD

**Issue by BlackDex** [mariospr/compact-quick-settings-gnome-shell-extension#2] opened 2022-11-21 08:37 UTC
Hello there,

First, thanks for this extension, I like the more compact version also.
Though i do have some small issues.

I use two other extensions, which extend the functionality of the quick settings by adding a sub-menu for bluetooth, and an extension which adds a menu for gsconnect (kde-connect).

The whole `gsconnect` menu is disappeared, and the sub-menu for the bluetooth is also gone.
Not sure if that is something this extension can fix.

Default:
![without-compact-settings](https://user-images.githubusercontent.com/610450/203003256-b1bb6266-205c-41cb-9882-60a60a170581.png)

With Compact Settings:
![with-compact-settings](https://user-images.githubusercontent.com/610450/203003268-6f748d95-f16c-4acc-8e45-43ed1c3738c8.png)

Extensions used:
GSConnect: https://github.com/GSConnect/gnome-shell-extension-gsconnect
Bluetooth Quick Connect: https://github.com/bjarosze/gnome-bluetooth-quick-connect

**Comment by mariospr** [comment] 2022-11-21 13:03
Thanks for the report! Looking at the code of those two extensions, the problem seems simple: I created my own element and add it to the statusArea as `compactQuickSettings`, so what the extensions were modifying was the original menu instead, which is hidden while the compact version is shown.

Just not using a separate name and simply saving the old menu temporarily on a variable seems to fix the problem, so I've just landed https://github.com/mariospr/compact-quick-settings-gnome-shell-extension/commit/ee8ce041adca44856370a19cb7e8cd9bf5221597 for that. I've tested this with the two extensions and it seems to work for me, even thought the fix is clearly dependent on which extension gets enabled first, which is not great: if BT Quick Connect gets enabled first, then it won't work, only if it's enabled after enabling the Compact Quick Settings one.

This is not ideal, but at the same time I can see that the extensions get enabled in the right order when both are enabled and you restart the shell (either by logging out and back in, or by Alt+F2 -> 'r' -> ENTER), so perhaps it's good enough. See the screenshot below:

![image](https://user-images.githubusercontent.com/2197259/203061604-f445c8d0-a58c-4d16-aedc-745773441f86.png)

@BlackDex In any case, I'd appreciate if you could test this before I've upload another version to extensions.gnome.org. Would it be possible that you could take the file from https://raw.githubusercontent.com/mariospr/compact-quick-settings-gnome-shell-extension/master/extension.js and sue it to replace the one in `~/.local/share/gnome-shell/extensions/compact-quick-settings\@gnome-shell-extensions.mariospr.org/extension.js` ? Then restart the shell and report here whether that fixes the issue or not.

Thanks!

**Comment by BlackDex** [comment] 2022-11-21 14:10
Hello @mariospr , thanks for the quick response.

I have tried this, and it does seem to work for GSConnect, but not for the Bluetooth extension for some reason.
Sometimes it does when i reload `ALT+F2 > r`.

But most of the time it doesn't show the bluetooth extension.
Also, if i disable the Compact Quick Connect, it breaks the GSConnect extension.

I tried to add `GLib.usleep` with a sleep of 5 seconds to both `init` and `enable`, but that doesn't seem to do the job.
But, i also have no experience with gnome-shell extension development at all.

**Comment by mariospr** [comment] 2022-11-21 17:48
Hmm... I think I'll need to investigate this deeper then. When I started writing the extension I honestly was thinking of scratching my own itch and didn't think much about other extensions, which is why the solution of simply "borrowing" the shell's code for the menu looked not too bad. Still, I did spend some time trying to figure out other ways that didn't imply that borrowing but so far I could not find anything since the menu needs to be instantiated with 1 column only, right from the start, and then the different items added.

But perhaps there's a way I can do it better. I'll try to take another look when I have some time, see if I figure out a better solution that does not depend on the ordering, which clearly will broke extensions (and now I discovered the BT one I do really want to keep using it!).

Thanks again, and sorry for not fixing this completely just yet.

**Closed** 2022-11-21 19:07 UTC

**Comment by mariospr** [comment] 2022-11-21 19:23
I've checked this a bit more and I honestly don't see a way for fixing this without having a dependency in the order extensions are loaded, that does not imply changing the other extensions.

Basically, the problem is that I can't simply "reference" elements from the original quick settings so that, when the BT or the GS Connect changes that one, it will also change the compact quick settings and viceversa: in one hand I don't have a way to referencing those elements (e.g. `this._bluetooth`) as if the were C pointers, and even if there was a way that would not work anyway since trying to do that would break the parent-child relationships (i.e. one child can't have multiple parents). Therefore, in the end all I can do, I think, is to provide the extension as-is but with this last-minute twist of not adding a new `compactQuickSettings` element to the `statusArea`, but simply replacing the original `quickSettings` one with the compact version in-place (and restoring the original one when disabling the extension). That way, those other extensions like BT Quick Connect and GS Connect will find the right elements to modify in the compact quick settings **if those extensions are loaded afterwards**.

What could be done, I think, would be to modify those extensions so that they are aware when the statusArea changes so that, whenever the `statusArea['quickSettings']` gets modified by any extension (not just this one), they force a reload of themselves. This way they would protect against any extension providing their own version of this menu, and should work fine regardless of the order they are loaded.

But from the point of view of this Compact Quick Settings extension, I don't think there's much more than can be done.

**Comment by mariospr** [comment] 2022-11-21 19:24
Also, a quick note on that for me this works fine like 100% of the times (when logging in and when using ALT+F2 -> r).

**Comment by mariospr** [comment] 2022-11-21 19:56
In case it helps, I've seen in `extensionSystem.js` that [it seems the order in which extensions are automatically enabled depend on the order they are stored in the GSetting `/org/gnome/shell/enabled-extensions` key](https://github.com/GNOME/gnome-shell/blob/main/js/ui/extensionSystem.js#L509) (well it depends on more things, but it looks like the original list is retrieved as-is from that GSetting key), so one thing that might help would be to **manually edit that key** (e.g. using _dconf Editor_) and make sure that you put `'compact-quick-settings@gnome-shell-extensions.mariospr.org'` as the first item in the list referenced by such key.

**Comment by mariospr** [comment] 2022-11-22 12:12
Thanks for the additional info! As I said, I don't think there's a good solution right now from the pov of this extension, so I'm happy you found a workaround that works for you (and also that explains why it works Ok for me already).
